from model.predictor import CLASS_NAMES, CLINICAL_NOTES


def generate_report(prediction: dict,
                    patient_id: str = 'UNKNOWN',
                    idh_status: str = 'Unknown',
                    codel_status: str = 'Unknown',
                    mgmt_status: str = 'Unknown') -> str:
    """
    Generate a WHO 2021 structured natural language report
    from a prediction dict returned by GliomaPredictor.predict()
    """
    pred  = prediction['predicted_class']
    conf  = prediction['confidence']
    unc   = prediction['uncertainty']
    level = prediction['confidence_level']
    proto = prediction['nearest_proto']
    near  = prediction['nearest_class']
    sim   = prediction['similarity_score']
    probs = prediction['mean_probs']
    stds  = prediction['std_probs']
    unc_f = prediction['uncertain_flag']

    unc_note = (
        '⚠️  UNCERTAIN — near decision boundary. '
        'Radiologist review strongly recommended.'
        if unc_f else
        'Within normal confidence range.'
    )

    report = f"""
╔══════════════════════════════════════════════════════════╗
║       XAI GLIOMA STRATIFICATION REPORT                  ║
║       CG-MAF + Prototype Learning System                 ║
╚══════════════════════════════════════════════════════════╝

PATIENT ID    : {patient_id}
GENERATED BY  : GliomaXAI Research Prototype (FYP CB011675)

──────────────────────────────────────────────────────────
PREDICTION (WHO 2021 Classification)
──────────────────────────────────────────────────────────
Predicted Subtype : {pred.upper()}
Confidence        : {conf:.1%}  [{level}]
Uncertainty       : ±{unc:.3f}
Status            : {unc_note}

Class Probabilities (mean ± std over 50 MC passes):
  Glioblastoma      : {probs[0]:.3f} ± {stds[0]:.3f}
  Astrocytoma       : {probs[1]:.3f} ± {stds[1]:.3f}
  Oligodendroglioma : {probs[2]:.3f} ± {stds[2]:.3f}

──────────────────────────────────────────────────────────
ANTE-HOC EXPLANATION (Prototype Reasoning)
──────────────────────────────────────────────────────────
Reasoning Method  : Case-Based Prototype Learning
Nearest Prototype : Prototype {proto} of {near.upper()} class
Similarity Score  : {sim:.4f} (1.0 = identical, 0.0 = different)

This prediction is explained by case-based reasoning —
the patient's MRI pattern most closely matches a learned
prototype from the training data. This explanation is
structurally embedded in the model (ante-hoc), not
generated after prediction (post-hoc).

Unlike Grad-CAM heatmaps, prototype explanations are:
  ✓ Stable under small input perturbations
  ✓ Causally linked to the model decision
  ✓ Comparable to radiologist case-based reasoning

──────────────────────────────────────────────────────────
MOLECULAR CONTEXT
──────────────────────────────────────────────────────────
IDH Mutation  : {idh_status}
1p/19q Status : {codel_status}
MGMT Status   : {mgmt_status}

──────────────────────────────────────────────────────────
CLINICAL NOTE (WHO 2021 CNS Tumor Classification)
──────────────────────────────────────────────────────────
{CLINICAL_NOTES.get(pred, 'N/A')}

──────────────────────────────────────────────────────────
EVALUATION METRICS (on held-out test set)
──────────────────────────────────────────────────────────
These metrics were computed on 21 locked test patients:
  • Perturbation Stability : prototype assignments stable
    under Gaussian noise (σ=0.05) across 10 runs
  • Activation Precision   : attention overlap with tumor mask
  • AOPC Deletion          : confidence drop on pixel removal

──────────────────────────────────────────────────────────
⚠️  DISCLAIMER
──────────────────────────────────────────────────────────
This report is produced by a RESEARCH PROTOTYPE developed
as part of an undergraduate FYP at the University of
Staffordshire. It is NOT validated for clinical use and
must NOT be used as a basis for medical diagnosis or
treatment decisions without qualified clinical review.

Supervisor: Ms. M.F.F. Nuha | Student: CB011675
══════════════════════════════════════════════════════════
"""
    return report